### ISSUE TITLE
Maximum Tabs limit does not seem to work in VS 2013

### ISSUE THREAD

**Issue by jgyo** [davemckeown/TidyTabs-VisualStudio#3]
I have installed Tidy-Tabs in VS 2013 Profession and have configured it with the following settings:

Close on save: True
Maximum Open Tabs: 6
Open Tab Threshold: 4
Timeout Minutes: 10

Now within the editor I have 11 documents opened, a combination of Xaml and CS documents. Three of documents are pinned, eight are not.

When I press Ctrl-Alt-Esc or else when I save a document none of the documents are closed, although most of the documents have not be view for over ten minutes.

**Comment by davemckeown** [comment]
Fixed in PR #9
