### ISSUE TITLE
Icon and Preview images are not correct

### ISSUE THREAD

**Issue by madskristensen** [davemckeown/TidyTabs-VisualStudio#7]
The icon should be 90x90px and the preview image should be 175x175px.

Currently there is no preview image at all. I've found that having pixel perfect images will help the download count significantly. The current icon doesn't look like it represents a serious extension. If you would like, I can help with some good images?

**Comment by davemckeown** [comment]
Thanks for pointing this out.

I am definitely open to replacing the icon and adding a preview image and would welcome any contributions.

**Comment by davemckeown** [comment]
Merged new icons in PR #8 

Thanks!!
